### PR TITLE
Names should be changed to container_runtime instead of just container

### PR DESCRIPTION
**Pull request by rhatdan**
Since this policy is controlling the containers runtimes, not the containers.
I would rather save container_t for the name of the processes running in the
container.

### CODE REVIEW

**Comment by lsm5** [comment]
I'm seeing avc denials with this:


Oct 03 14:36:18 naruto systemd[1]: Started Docker Storage Setup.
-- Subject: Unit docker-storage-setup.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker-storage-setup.service has finished starting up.
-- 
-- The start-up result is done.
Oct 03 14:36:18 naruto audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=docker-storage-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 03 14:36:18 naruto audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=docker-storage-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Oct 03 14:36:18 naruto systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Oct 03 14:36:18 naruto dockerd-current[32006]: time="2016-10-03T14:36:18.377799335-05:00" level=fatal msg="Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid"
Oct 03 14:36:18 naruto systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 14:36:18 naruto audit[1]: AVC avc:  denied  { signal } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=process permissive=0
Oct 03 14:36:18 naruto audit[1]: AVC avc:  denied  { sigkill } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=process permissive=0
Oct 03 14:36:18 naruto audit[1]: AVC avc:  denied  { signal } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=process permissive=0
Oct 03 14:36:18 naruto audit[1]: AVC avc:  denied  { sigkill } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=process permissive=0
Oct 03 14:36:18 naruto systemd[1]: docker.service: Failed to kill control group /system.slice/docker.service, ignoring: Permission denied
Oct 03 14:36:18 naruto systemd[1]: docker.service: Killing process 20160 (dockerd-current) with signal SIGKILL.
Oct 03 14:36:18 naruto systemd[1]: docker.service: Failed to kill control group /system.slice/docker.service, ignoring: Permission denied
Oct 03 14:36:18 naruto audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=docker comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Oct 03 14:36:18 naruto systemd[1]: docker.service: Failed to kill control group /system.slice/docker.service, ignoring: Permission denied
Oct 03 14:36:18 naruto systemd[1]: docker.service: Killing process 20160 (dockerd-current) with signal SIGKILL.
Oct 03 14:36:18 naruto systemd[1]: docker.service: Failed to kill control group /system.slice/docker.service, ignoring: Permission denied
Oct 03 14:36:18 naruto systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Oct 03 14:36:18 naruto systemd[1]: docker.service: Unit entered failed state.
Oct 03 14:36:18 naruto systemd[1]: docker.service: Failed with result 'exit-code'.
Oct 03 14:36:18 naruto sudo[31961]: pam_unix(sudo:session): session closed for user root
Oct 03 14:36:18 naruto audit[31961]: USER_END pid=31961 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_systemd,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=succes
Oct 03 14:36:18 naruto audit[31961]: CRED_DISP pid=31961 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'

**Comment by rhatdan** [comment]
Did you update a docker to the first container-selinux and then update a second time? 

In the first one I aliased docker_t -> container_t but I did not map container_t -> container_runtime_t.

But that should not be supported.  Could you try again by installing docker-selinux and then restart the docker daemon and make sure it is running as docker_t. Then update the new package and see if it running as container_runtime_t.

**Comment by lsm5** [comment]
ah I see, with a prior docker-selinux from rawhide, if I upgrade to this version, it works fine. scratch building @ http://koji.fedoraproject.org/koji/taskinfo?taskID=15927596 if you wanna check it out

**Comment by rhatdan** [comment]
Excellent.

**Comment by rhatdan** [comment]
Lets build this for Rawhide.

**Comment by lsm5** [comment]
cool, on it..

**Pull request merged**
