### PR TITLE
Rhel 1.12

### PR DESCRIPTION
**Pull request by lsm5**
@rhatdan rebased rhel-1.12 branch on master

### CODE REVIEW

**Comment by lsm5** [comment]
hmm not sure why it's listing all these commits, let me get back

**Comment by lsm5** [comment]
na looks right I guess.

**Comment by rhatdan** [comment]
LGTM.

**Comment by rhatdan** [comment]
@lsm5 Looks like we have conflicts.

**Comment by lsm5** [comment]
cherry-picked commits from master into RHEL-1.12. Should be ok now

**Pull request merged**
