### PR TITLE
Rhel 1.12

### PR DESCRIPTION
**Pull request by lsm5**
@rhatdan ptal

### CODE REVIEW

**Comment by lsm5** [comment]
revising.. let me get back

**Comment by rhatdan** [comment]
TE files are fine.  Changes to interface file should not be done.  Should also have changes to the fc file.

**Comment by lsm5** [comment]
@rhatdan `container.fc` was the same in both RHEL and Fedora. Does it need any changes in RHEL in that case?

**Comment by rhatdan** [comment]
Nope they should be the same.  I am pushing an update to container.te that should also end up in RHEL version.

**Comment by lsm5** [comment]
ack, do the current commits on this PR look good then ?

**Pull request merged**
